```python
# 23 - RSI 14 Slope Momentum
# Source: The Independent Quant | theindependentquant.com
# The RSI 14 Slope Momentum strategy is a systematic trading approach designed to capture momentum in the SPY, an ETF that tracks the S&P 500 index. The strategy utilizes the Relative Strength Index (RSI), a popular momentum oscillator, specifically focusing on the 14-period RSI. The signal is generated by calculating the slope of the RSI over a specified period, typically 14 days. When the slope is positive, it indicates upward momentum, suggesting a potential buy signal for SPY. Conversely, a negative slope suggests downward momentum, indicating a potential sell signal or an exit from a long position.
# References:
# (No external references)
# Usage instructions: Run the script with optional arguments for ticker, start date, end date, and plot flag. Example: python script.py --ticker SPY --start 2010-01-01 --end 2023-10-01 --plot

import argparse
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
from datetime import datetime

# Constants
RSI_PERIOD = 14
SLOPE_PERIOD = 14

def download_data(ticker='SPY', start='2010-01-01', end=None):
    if end is None:
        end = datetime.today().strftime('%Y-%m-%d')
    df = yf.download(ticker, start=start, end=end)
    return df

def compute_signal(df):
    df['RSI'] = compute_rsi(df['Close'], RSI_PERIOD)
    df['RSI_Slope'] = df['RSI'].diff(SLOPE_PERIOD)
    df['Signal'] = np.where(df['RSI_Slope'] > 0, 1, 0)
    df['Signal'] = df['Signal'].shift(1)  # Prevent look-ahead bias
    return df

def compute_rsi(series, period):
    delta = series.diff(1)
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def backtest(df):
    df['Strategy_Returns'] = df['Signal'] * df['Close'].pct_change()
    df['Cumulative_Strategy'] = (1 + df['Strategy_Returns']).cumprod()
    df['Cumulative_Market'] = (1 + df['Close'].pct_change()).cumprod()
    return df

def performance(df):
    cagr = ((df['Cumulative_Strategy'].iloc[-1]) ** (252.0/len(df))) - 1
    daily_returns = df['Strategy_Returns'].dropna()
    sharpe_ratio = np.sqrt(252) * daily_returns.mean() / daily_returns.std()
    downside_returns = daily_returns[daily_returns < 0]
    sortino_ratio = np.sqrt(252) * daily_returns.mean() / downside_returns.std()
    max_drawdown = (df['Cumulative_Strategy'].cummax() - df['Cumulative_Strategy']).max()
    calmar_ratio = cagr / max_drawdown
    return {
        'CAGR': cagr,
        'Sharpe Ratio': sharpe_ratio,
        'Sortino Ratio': sortino_ratio,
        'Calmar Ratio': calmar_ratio,
        'Max Drawdown': max_drawdown
    }

def print_results(perf, ticker):
    print(f"Performance Summary for {ticker}:")
    for key, value in perf.items():
        print(f"{key}: {value:.2f}")

def plot_results(df, ticker, strategy_name):
    plt.figure(figsize=(14, 7))
    plt.plot(df.index, df['Cumulative_Strategy'], label='Strategy')
    plt.plot(df.index, df['Cumulative_Market'], label='Buy and Hold')
    plt.title(f'{strategy_name} Strategy vs Buy and Hold')
    plt.xlabel('Date')
    plt.ylabel('Cumulative Returns')
    plt.legend()
    plt.show()

def todays_signal(ticker):
    df = download_data(ticker, start='2023-01-01')
    df = compute_signal(df)
    latest_signal = df['Signal'].iloc[-1]
    print(f"Today's signal for {ticker} is {'Buy' if latest_signal == 1 else 'Sell/Stay Out'}")

def main():
    parser = argparse.ArgumentParser(description='RSI 14 Slope Momentum Strategy')
    parser.add_argument('--ticker', type=str, default='SPY', help='Ticker symbol')
    parser.add_argument('--start', type=str, default='2010-01-01', help='Start date')
    parser.add_argument('--end', type=str, default=datetime.today().strftime('%Y-%m-%d'), help='End date')
    parser.add_argument('--plot', action='store_true', help='Plot equity curve')
    args = parser.parse_args()

    df = download_data(args.ticker, args.start, args.end)
    df = compute_signal(df)
    df = backtest(df)
    perf = performance(df)
    print_results(perf, args.ticker)

    if args.plot:
        plot_results(df, args.ticker, '#23 - RSI 14 Slope Momentum')

    todays_signal(args.ticker)

if __name__ == '__main__':
    main()
```