```python
# 29 - Consolidation Box Breakout
# Source: The Independent Quant | theindependentquant.com
# 
# The Consolidation Box Breakout strategy is designed to identify and capitalize on periods when the SPY, an ETF that tracks the S&P 500, breaks out of a defined price range. This strategy aims to pinpoint moments when the market is likely to experience a significant move following a period of low volatility or sideways trading. The signal is generated by identifying a "consolidation box," which is a range where the price of SPY trades within a relatively narrow band for a specific number of days. Once the price breaks out of this box, either above the upper boundary or below the lower boundary, a trade is initiated in the direction of the breakout.
# 
# References:
# (No external references)
# 
# Usage instructions:
# Run the script with optional arguments for ticker, start date, end date, and plot flag.
# Example: python script.py --ticker SPY --start 2010-01-01 --end 2023-10-01 --plot

import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
from datetime import datetime

# Constants
LOOKBACK_DAYS = 20
BREAKOUT_THRESHOLD = 0.01

def download_data(ticker, start, end):
    """Download historical data for the given ticker."""
    df = yf.download(ticker, start=start, end=end)
    return df

def compute_signal(df):
    """Compute the breakout signal based on consolidation box breakout strategy."""
    df['High_Max'] = df['High'].rolling(window=LOOKBACK_DAYS).max()
    df['Low_Min'] = df['Low'].rolling(window=LOOKBACK_DAYS).min()
    df['Signal'] = np.where(df['Close'] > df['High_Max'].shift(1) * (1 + BREAKOUT_THRESHOLD), 1, 
                            np.where(df['Close'] < df['Low_Min'].shift(1) * (1 - BREAKOUT_THRESHOLD), -1, 0))
    return df

def backtest(df):
    """Backtest the strategy and compute returns."""
    df['Position'] = df['Signal'].shift(1).fillna(0)
    df['Strategy_Returns'] = df['Position'] * df['Close'].pct_change()
    df['Cumulative'] = (1 + df['Strategy_Returns']).cumprod()
    return df

def performance(df):
    """Calculate performance metrics."""
    cagr = (df['Cumulative'].iloc[-1])**(252/len(df)) - 1
    strategy_returns = df['Strategy_Returns'].dropna()
    sharpe_ratio = np.sqrt(252) * strategy_returns.mean() / strategy_returns.std()
    downside_returns = strategy_returns[strategy_returns < 0]
    sortino_ratio = np.sqrt(252) * strategy_returns.mean() / downside_returns.std()
    max_drawdown = (df['Cumulative'].cummax() - df['Cumulative']).max()
    calmar_ratio = cagr / max_drawdown
    return {
        'CAGR': cagr,
        'Sharpe Ratio': sharpe_ratio,
        'Sortino Ratio': sortino_ratio,
        'Calmar Ratio': calmar_ratio,
        'Max Drawdown': max_drawdown
    }

def print_results(perf, ticker):
    """Print the performance results."""
    print(f"Performance Metrics for {ticker}:")
    for key, value in perf.items():
        print(f"{key}: {value:.2f}")

def plot_results(df, ticker, strategy_name):
    """Plot the equity curve and buy-and-hold strategy."""
    df['Buy_Hold'] = (1 + df['Close'].pct_change()).cumprod()
    plt.figure(figsize=(12, 6))
    plt.plot(df.index, df['Cumulative'], label=f'{strategy_name} Strategy')
    plt.plot(df.index, df['Buy_Hold'], label='Buy and Hold', linestyle='--')
    plt.title(f'{ticker} - {strategy_name} vs Buy and Hold')
    plt.xlabel('Date')
    plt.ylabel('Cumulative Returns')
    plt.legend()
    plt.show()

def todays_signal(ticker):
    """Print today's signal based on the latest data."""
    end = datetime.today().strftime('%Y-%m-%d')
    start = (datetime.today() - pd.Timedelta(days=LOOKBACK_DAYS*2)).strftime('%Y-%m-%d')
    df = download_data(ticker, start, end)
    df = compute_signal(df)
    latest_signal = df['Signal'].iloc[-1]
    print(f"Today's signal for {ticker}: {'Long' if latest_signal == 1 else 'Short' if latest_signal == -1 else 'Neutral'}")

def main():
    """Main function to wire everything together."""
    parser = argparse.ArgumentParser(description='Consolidation Box Breakout Strategy')
    parser.add_argument('--ticker', type=str, default='SPY', help='Ticker symbol')
    parser.add_argument('--start', type=str, default='2010-01-01', help='Start date (YYYY-MM-DD)')
    parser.add_argument('--end', type=str, default=datetime.today().strftime('%Y-%m-%d'), help='End date (YYYY-MM-DD)')
    parser.add_argument('--plot', action='store_true', help='Plot equity curve')
    args = parser.parse_args()

    df = download_data(args.ticker, args.start, args.end)
    df = compute_signal(df)
    df = backtest(df)
    perf = performance(df)
    print_results(perf, args.ticker)

    if args.plot:
        plot_results(df, args.ticker, 'Consolidation Box Breakout')

    todays_signal(args.ticker)

if __name__ == '__main__':
    main()
```